# Datasource configuration
spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: VVmDryGvzKIPWGxrzlqgWJyaiZEntYPs

  jpa:
    hibernate:
      ddl-auto: update
